# Generated by Django 5.0.7 on 2024-08-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_platform_movies_platform_alter_movies_ratings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='reviews',
            name='full_name',
            field=models.CharField(default='abc', max_length=200),
        ),
    ]
