# Generated by Django 5.0.7 on 2024-08-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_reviews_email_reviews_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
    ]
