# Generated by Django 5.0.7 on 2024-08-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_reviews_email_alter_reviews_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='ratings',
            field=models.FloatField(),
        ),
    ]
