# Generated by Django 5.0.7 on 2024-08-03 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_reviews_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='ratings',
        ),
        migrations.AlterField(
            model_name='movies',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='base.platform'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='base.movies'),
        ),
    ]
