# Generated by Django 5.0.7 on 2024-08-04 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_user_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
