# Generated by Django 5.0.7 on 2024-08-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_watchlist_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
